# Generated by Django 5.1 on 2024-08-29 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShortCodeOrNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InitiatorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaCommandId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occassion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_url', models.CharField(blank=True, max_length=200, null=True)),
                ('validation_url', models.CharField(blank=True, max_length=200, null=True)),
                ('company_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_short_code_or_number', to='mpesa.companyshortcodeornumber')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='mpesa.initiatorname')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('account_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_reference', to='mpesa.mpesacommandid')),
                ('command_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_id', to='mpesa.mpesacommandid')),
                ('identifier_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identifier_type', to='mpesa.identifiertype')),
                ('initiator_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_name', to='mpesa.initiatorname')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcode', to='mpesa.occassion')),
                ('party_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_a', to='mpesa.companyshortcodeornumber')),
                ('party_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_b', to='mpesa.companyshortcodeornumber')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='mpesa.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator_conversation_id', models.CharField(blank=True, max_length=200, null=True)),
                ('response_description', models.CharField(blank=True, max_length=200, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=200, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('response_code', models.CharField(blank=True, max_length=200, null=True)),
                ('result_description', models.CharField(blank=True, max_length=200, null=True)),
                ('result_code', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='mpesa.transaction')),
            ],
        ),
    ]
